# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserver_name', models.CharField(max_length=100)),
                ('reserver_email', models.EmailField(max_length=254)),
                ('reserver_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Subject'),
        ),
    ]
