# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.IntegerField(),
        ),
    ]
