# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160817_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='number',
        ),
    ]
