# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_place_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='gps_location_data',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location',
        ),
        migrations.AddField(
            model_name='place',
            name='locations',
            field=models.ManyToManyField(to='event.SpaceTimePoint'),
        ),
    ]
