# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='image', max_length=100),
        ),
    ]
