# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20160909_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
