# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='event',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_point_set', to='event.Place'),
        ),
    ]
