# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20161103_1406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventLocation',
            new_name='PlaceLocation',
        ),
    ]
