# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20161103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='no title', max_length=100),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='extra_facilities',
            field=models.ManyToManyField(blank=True, related_name='proposal', to='event.Facility'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Subject'),
        ),
    ]
