# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20161205_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
