# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20161206_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='name',
        ),
        migrations.AddField(
            model_name='facility',
            name='english_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='farsi_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
