# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20161207_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='farsi_name',
        ),
        migrations.AddField(
            model_name='facility',
            name='name',
            field=models.CharField(default='hey', max_length=100),
        ),
    ]
