# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20161207_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='name',
        ),
        migrations.AddField(
            model_name='facility',
            name='english_name',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='persian_name',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
