# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_auto_20161207_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='files/aboutus')),
                ('english_text', models.CharField(max_length=10000)),
                ('persian_text', models.CharField(max_length=10000)),
            ],
        ),
    ]
