# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='last_change_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proposal',
            name='save_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='submission_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
