# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20170104_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('not submitted', 'Not submitted'), ('pending approval', 'Pending approval'), ('submitted', 'Submitted')], default='not submitted', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='status_fa',
            field=models.CharField(choices=[('ثبت نشده', 'ثبت نشده'), ('در انتظار تایید', 'در انتظار تایید'), ('ثبت شده', 'ثبت شده')], default='ط«ط¨طھ ظ†ط´ط¯ظ‡', max_length=100),
            preserve_default=False,
        ),
    ]
