# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20170208_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('not submitted', 'not submitted'), ('pending approval', 'pending approval'), ('submitted', 'submitted')], max_length=100),
        ),
    ]
