# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_auto_20170208_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Subject'),
        ),
    ]
