# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_auto_20170208_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='jalali_end_date_txt',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='jalali_start_date_txt',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
