# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_auto_20170209_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='schedule_txt',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
